name: Run Build

on:
  pull_request:
    types: [ opened, synchronize ]
    branches: [ main, development ]  # update later to remove development
  push:
      branches: [ "main" ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    name: Run pre-commit hooks
    steps:
    - uses: actions/checkout@v4

    - name: Install poetry
      run: python -m pip install poetry==1.5.1

    - name: Install Pre-commit
      run: python -m pip install pre-commit

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'poetry'
    - name: Install dependencies
      run: poetry install --with dev

    - name: Set up hooks
      run: poetry run pre-commit install

    - name: Run pre-commit hooks
      run: poetry run pre-commit run --all-files
  
  release-drafter:
    runs-on: ubuntu-latest
    name: Generate release notes
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Release Drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-name: ".github/release-drafter.yml"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}